# Generated by Django 3.2.10 on 2021-12-16 15:18

from django.db import migrations
import wagtail.core.fields
import wagtail_references.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='bib_reference',
            field=wagtail.core.fields.StreamField([('ref', wagtail_references.blocks.ReferenceChooserBlock(target_model='wagtail_references.reference'))], blank=True),
        ),
    ]
