# Generated by Django 3.2.10 on 2021-12-19 13:49

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_references.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_blogpage_bib_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='bib_reference',
            field=wagtail.core.fields.StreamField([('ref', wagtail_references.blocks.ReferenceChooserBlock(target_model='wagtail_references.reference')), ('richtext', wagtail.core.blocks.RichTextBlock())], blank=True),
        ),
    ]
