# Generated by Django 3.2.10 on 2021-12-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_references', '0004_reference_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='bibjson',
            field=models.JSONField(),
        ),
    ]
